services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env 
    restart: always
